### ISSUE TITLE
My friend's bux is broken

### ISSUE THREAD

**Issue by rydens** [robmuh/go-wishes#4]
Whenever he runs bux, he gets the question, then ```strconv.ParseInt: parsing "": invalid syntax```
If someone else tries to see his bux, they get the same error.

**Comment by retep-mathwizard** [comment]
Who's bux is this?

**Comment by rydens** [comment]
```applepie```'s

**Comment by rydens** [comment]
```bux applepie```

**Comment by rydens** [comment]
Is anyone going to help me??
